/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Tribunal } from "./Tribunal";
export * as factories from "./factories";
export { Tribunal__factory } from "./factories/Tribunal__factory";
