/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace Tribunal {
  export type ProofStruct = {
    invoiceId: string;
    approverIds: string[];
    dataHash: BytesLike;
    timestamp: BigNumberish;
    exists: boolean;
  };

  export type ProofStructOutput = [
    invoiceId: string,
    approverIds: string[],
    dataHash: string,
    timestamp: bigint,
    exists: boolean
  ] & {
    invoiceId: string;
    approverIds: string[];
    dataHash: string;
    timestamp: bigint;
    exists: boolean;
  };
}

export interface TribunalInterface extends Interface {
  getFunction(
    nameOrSignature: "getProof" | "mintProof" | "owner" | "proofs"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "ProofMinted"): EventFragment;

  encodeFunctionData(functionFragment: "getProof", values: [string]): string;
  encodeFunctionData(
    functionFragment: "mintProof",
    values: [string, string[], BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "proofs", values: [string]): string;

  decodeFunctionResult(functionFragment: "getProof", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "mintProof", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "proofs", data: BytesLike): Result;
}

export namespace ProofMintedEvent {
  export type InputTuple = [
    invoiceId: string,
    approverIds: string[],
    dataHash: BytesLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    invoiceId: string,
    approverIds: string[],
    dataHash: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    invoiceId: string;
    approverIds: string[];
    dataHash: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface Tribunal extends BaseContract {
  connect(runner?: ContractRunner | null): Tribunal;
  waitForDeployment(): Promise<this>;

  interface: TribunalInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getProof: TypedContractMethod<
    [invoiceId: string],
    [Tribunal.ProofStructOutput],
    "view"
  >;

  mintProof: TypedContractMethod<
    [invoiceId: string, approverIds: string[], dataHash: BytesLike],
    [void],
    "nonpayable"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  proofs: TypedContractMethod<
    [arg0: string],
    [
      [string, string, bigint, boolean] & {
        invoiceId: string;
        dataHash: string;
        timestamp: bigint;
        exists: boolean;
      }
    ],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getProof"
  ): TypedContractMethod<
    [invoiceId: string],
    [Tribunal.ProofStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "mintProof"
  ): TypedContractMethod<
    [invoiceId: string, approverIds: string[], dataHash: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "proofs"
  ): TypedContractMethod<
    [arg0: string],
    [
      [string, string, bigint, boolean] & {
        invoiceId: string;
        dataHash: string;
        timestamp: bigint;
        exists: boolean;
      }
    ],
    "view"
  >;

  getEvent(
    key: "ProofMinted"
  ): TypedContractEvent<
    ProofMintedEvent.InputTuple,
    ProofMintedEvent.OutputTuple,
    ProofMintedEvent.OutputObject
  >;

  filters: {
    "ProofMinted(string,string[],bytes32,uint256)": TypedContractEvent<
      ProofMintedEvent.InputTuple,
      ProofMintedEvent.OutputTuple,
      ProofMintedEvent.OutputObject
    >;
    ProofMinted: TypedContractEvent<
      ProofMintedEvent.InputTuple,
      ProofMintedEvent.OutputTuple,
      ProofMintedEvent.OutputObject
    >;
  };
}
